# Copyright 2014-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "gtk+" %}
{% set version = "3.24.12" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "1384eba5614fed160044ae0d32369e3df7b4f517b03f4b1f24d383e528f4be83" %}

package:
  name: gtk3  # note customization
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - meson.patch

build:
  number: 0
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_compatible('gtk3', max_pin='x') }}

requirements:
  build:
    - meson
    - ninja
    - pkg-config
    - python >=3.5
    - {{ compiler('c') }}
  host:
    - atk
    - cairo {{ cairo }}
    - epoxy 1.*
    - fontconfig {{ fontconfig }}
    - gdk-pixbuf {{ gdk_pixbuf }}
    - glib {{ glib }}
    - gobject-introspection 1.*
    - pango {{pango}}
  run:
    - gdk-pixbuf {{ gdk_pixbuf }}
    - glib {{ glib }}
    - pango {{ pango }}

test:
  commands:
    # Check that the binaries can run -- instigated by Meson Linux rpath issues
    # `gtk-builder-tool` and `gtk-query-settings` require a display
    - gtk-encode-symbolic-svg --help
    - gtk-launch --help
    - gtk-query-immodules-3.0
    - gtk-update-icon-cache --help

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: version 3 of the Gtk+ graphical toolkit
