# Copyright 2018-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "epoxy" %}
{% set version = "1.5.3" %}
{% set sha256 = "002958c5528321edd53440235d3c44e71b5b1e09b9177e8daf677450b6c4433d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anholt/libepoxy/releases/download/{{ version }}/libepoxy-{{ version }}.tar.xz
  sha256: {{ sha256 }}


build:
  number: 0
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_compatible('epoxy', max_pin='x.x') }}

requirements:
  build:
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
    - python >=3.5
    - {{ compiler('c') }}

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/anholt/libepoxy
  license: MIT
  license_file: COPYING
  summary: 'A library for handling OpenGL function pointer management for you.'
